//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrevueDataSender.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class View : global::System.Configuration.ApplicationSettingsBase {
        
        private static View defaultInstance = ((View)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new View())));
        
        public static View Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int Z2IListingsDGV_AdjDayofYear_ColWidth {
            get {
                return ((int)(this["Z2IListingsDGV_AdjDayofYear_ColWidth"]));
            }
            set {
                this["Z2IListingsDGV_AdjDayofYear_ColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int Z2IListingsDGV_SourceID_ColWidth {
            get {
                return ((int)(this["Z2IListingsDGV_SourceID_ColWidth"]));
            }
            set {
                this["Z2IListingsDGV_SourceID_ColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int Z2IListingsDGV_TimeSlot_ColWidth {
            get {
                return ((int)(this["Z2IListingsDGV_TimeSlot_ColWidth"]));
            }
            set {
                this["Z2IListingsDGV_TimeSlot_ColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int Z2IListingsDGV_Attribute_ColWidth {
            get {
                return ((int)(this["Z2IListingsDGV_Attribute_ColWidth"]));
            }
            set {
                this["Z2IListingsDGV_Attribute_ColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public int Z2IListingsDGV_Title_ColWidth {
            get {
                return ((int)(this["Z2IListingsDGV_Title_ColWidth"]));
            }
            set {
                this["Z2IListingsDGV_Title_ColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("160")]
        public int Z2IListingsDGV_Subtitle_ColWidth {
            get {
                return ((int)(this["Z2IListingsDGV_Subtitle_ColWidth"]));
            }
            set {
                this["Z2IListingsDGV_Subtitle_ColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int Z2IListingsDGV_Description_ColWidth {
            get {
                return ((int)(this["Z2IListingsDGV_Description_ColWidth"]));
            }
            set {
                this["Z2IListingsDGV_Description_ColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int Z2ILineupDGV_SourceID_ColWidth {
            get {
                return ((int)(this["Z2ILineupDGV_SourceID_ColWidth"]));
            }
            set {
                this["Z2ILineupDGV_SourceID_ColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int Z2ILineupDGV_Number_ColWidth {
            get {
                return ((int)(this["Z2ILineupDGV_Number_ColWidth"]));
            }
            set {
                this["Z2ILineupDGV_Number_ColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int Z2ILineupDGV_ID_ColWidth {
            get {
                return ((int)(this["Z2ILineupDGV_ID_ColWidth"]));
            }
            set {
                this["Z2ILineupDGV_ID_ColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int Z2ILineupDGV_RedHiLt_ColWidth {
            get {
                return ((int)(this["Z2ILineupDGV_RedHiLt_ColWidth"]));
            }
            set {
                this["Z2ILineupDGV_RedHiLt_ColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int Z2ILineupDGV_SBS_ColWidth {
            get {
                return ((int)(this["Z2ILineupDGV_SBS_ColWidth"]));
            }
            set {
                this["Z2ILineupDGV_SBS_ColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int Z2ILineupDGV_PTagDisabled_ColWidth {
            get {
                return ((int)(this["Z2ILineupDGV_PTagDisabled_ColWidth"]));
            }
            set {
                this["Z2ILineupDGV_PTagDisabled_ColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int Z2ILineupDGV_PPVSrc_ColWidth {
            get {
                return ((int)(this["Z2ILineupDGV_PPVSrc_ColWidth"]));
            }
            set {
                this["Z2ILineupDGV_PPVSrc_ColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int Z2ILineupDGV_DittoEnable_ColWidth {
            get {
                return ((int)(this["Z2ILineupDGV_DittoEnable_ColWidth"]));
            }
            set {
                this["Z2ILineupDGV_DittoEnable_ColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int Z2ILineupDGV_LtBlueHiLt_ColWidth {
            get {
                return ((int)(this["Z2ILineupDGV_LtBlueHiLt_ColWidth"]));
            }
            set {
                this["Z2ILineupDGV_LtBlueHiLt_ColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int Z2ILineupDGV_StereoSrc_ColWidth {
            get {
                return ((int)(this["Z2ILineupDGV_StereoSrc_ColWidth"]));
            }
            set {
                this["Z2ILineupDGV_StereoSrc_ColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int Z2ILineupDGV_Daypart1_ColWidth {
            get {
                return ((int)(this["Z2ILineupDGV_Daypart1_ColWidth"]));
            }
            set {
                this["Z2ILineupDGV_Daypart1_ColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int Z2ILineupDGV_Daypart2_ColWidth {
            get {
                return ((int)(this["Z2ILineupDGV_Daypart2_ColWidth"]));
            }
            set {
                this["Z2ILineupDGV_Daypart2_ColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int Z2ILineupDGV_Daypart3_ColWidth {
            get {
                return ((int)(this["Z2ILineupDGV_Daypart3_ColWidth"]));
            }
            set {
                this["Z2ILineupDGV_Daypart3_ColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int Z2ILineupDGV_Daypart4_ColWidth {
            get {
                return ((int)(this["Z2ILineupDGV_Daypart4_ColWidth"]));
            }
            set {
                this["Z2ILineupDGV_Daypart4_ColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int Z2ILineupDGV_Daypart5_ColWidth {
            get {
                return ((int)(this["Z2ILineupDGV_Daypart5_ColWidth"]));
            }
            set {
                this["Z2ILineupDGV_Daypart5_ColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int Z2ILineupDGV_Daypart6_ColWidth {
            get {
                return ((int)(this["Z2ILineupDGV_Daypart6_ColWidth"]));
            }
            set {
                this["Z2ILineupDGV_Daypart6_ColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int ListingsDGV_AdjDayofYear_ColWidth {
            get {
                return ((int)(this["ListingsDGV_AdjDayofYear_ColWidth"]));
            }
            set {
                this["ListingsDGV_AdjDayofYear_ColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int ListingsDGV_SourceID_ColWidth {
            get {
                return ((int)(this["ListingsDGV_SourceID_ColWidth"]));
            }
            set {
                this["ListingsDGV_SourceID_ColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int ListingsDGV_TimeSlot_ColWidth {
            get {
                return ((int)(this["ListingsDGV_TimeSlot_ColWidth"]));
            }
            set {
                this["ListingsDGV_TimeSlot_ColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int ListingsDGV_Attribute_ColWidth {
            get {
                return ((int)(this["ListingsDGV_Attribute_ColWidth"]));
            }
            set {
                this["ListingsDGV_Attribute_ColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int ListingsDGV_Title_ColWidth {
            get {
                return ((int)(this["ListingsDGV_Title_ColWidth"]));
            }
            set {
                this["ListingsDGV_Title_ColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int LineupDGV_SourceID_ColWidth {
            get {
                return ((int)(this["LineupDGV_SourceID_ColWidth"]));
            }
            set {
                this["LineupDGV_SourceID_ColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int LineupDGV_Number_ColWidth {
            get {
                return ((int)(this["LineupDGV_Number_ColWidth"]));
            }
            set {
                this["LineupDGV_Number_ColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int LineupDGV_ID_ColWidth {
            get {
                return ((int)(this["LineupDGV_ID_ColWidth"]));
            }
            set {
                this["LineupDGV_ID_ColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int LineupDGV_Attribute_ColWidth {
            get {
                return ((int)(this["LineupDGV_Attribute_ColWidth"]));
            }
            set {
                this["LineupDGV_Attribute_ColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int LineupDGV_Daypart1_ColWidth {
            get {
                return ((int)(this["LineupDGV_Daypart1_ColWidth"]));
            }
            set {
                this["LineupDGV_Daypart1_ColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int LineupDGV_Daypart2_ColWidth {
            get {
                return ((int)(this["LineupDGV_Daypart2_ColWidth"]));
            }
            set {
                this["LineupDGV_Daypart2_ColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int LineupDGV_Daypart3_ColWidth {
            get {
                return ((int)(this["LineupDGV_Daypart3_ColWidth"]));
            }
            set {
                this["LineupDGV_Daypart3_ColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int LineupDGV_Daypart4_ColWidth {
            get {
                return ((int)(this["LineupDGV_Daypart4_ColWidth"]));
            }
            set {
                this["LineupDGV_Daypart4_ColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int LineupDGV_Daypart5_ColWidth {
            get {
                return ((int)(this["LineupDGV_Daypart5_ColWidth"]));
            }
            set {
                this["LineupDGV_Daypart5_ColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int LineupDGV_Daypart6_ColWidth {
            get {
                return ((int)(this["LineupDGV_Daypart6_ColWidth"]));
            }
            set {
                this["LineupDGV_Daypart6_ColWidth"] = value;
            }
        }
    }
}
