//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrevueDataSender {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class ListingColor : global::System.Configuration.ApplicationSettingsBase {
        
        private static ListingColor defaultInstance = ((ListingColor)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ListingColor())));
        
        public static ListingColor Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MovieRBSelected {
            get {
                return ((int)(this["MovieRBSelected"]));
            }
            set {
                this["MovieRBSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SportsRBSelected {
            get {
                return ((int)(this["SportsRBSelected"]));
            }
            set {
                this["SportsRBSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FamilyRBSelected {
            get {
                return ((int)(this["FamilyRBSelected"]));
            }
            set {
                this["FamilyRBSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int NewsRBSelected {
            get {
                return ((int)(this["NewsRBSelected"]));
            }
            set {
                this["NewsRBSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OtherRBSelected {
            get {
                return ((int)(this["OtherRBSelected"]));
            }
            set {
                this["OtherRBSelected"] = value;
            }
        }
    }
}
