//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrevueDataSender {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class ListingText : global::System.Configuration.ApplicationSettingsBase {
        
        private static ListingText defaultInstance = ((ListingText)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ListingText())));
        
        public static ListingText Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MovieTextCaseSelected {
            get {
                return ((int)(this["MovieTextCaseSelected"]));
            }
            set {
                this["MovieTextCaseSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AllTextCaseSelected {
            get {
                return ((int)(this["AllTextCaseSelected"]));
            }
            set {
                this["AllTextCaseSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int DisplayTVRatings {
            get {
                return ((int)(this["DisplayTVRatings"]));
            }
            set {
                this["DisplayTVRatings"] = value;
            }
        }
    }
}
