//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrevueDataSender {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class PrevueConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static PrevueConfig defaultInstance = ((PrevueConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PrevueConfig())));
        
        public static PrevueConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Grid_Hold_Time {
            get {
                return ((int)(this["Grid_Hold_Time"]));
            }
            set {
                this["Grid_Hold_Time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C")]
        public string Grid_Source_Channel_Order {
            get {
                return ((string)(this["Grid_Source_Channel_Order"]));
            }
            set {
                this["Grid_Source_Channel_Order"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Grid_Movie_Recap_Frequency {
            get {
                return ((int)(this["Grid_Movie_Recap_Frequency"]));
            }
            set {
                this["Grid_Movie_Recap_Frequency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int Grid_SBS_Frequency {
            get {
                return ((int)(this["Grid_SBS_Frequency"]));
            }
            set {
                this["Grid_SBS_Frequency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int Grid_SBS_TimeSlot_LookAhead {
            get {
                return ((int)(this["Grid_SBS_TimeSlot_LookAhead"]));
            }
            set {
                this["Grid_SBS_TimeSlot_LookAhead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int Scroll_SBS_TimeSlot_LookAhead {
            get {
                return ((int)(this["Scroll_SBS_TimeSlot_LookAhead"]));
            }
            set {
                this["Scroll_SBS_TimeSlot_LookAhead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G")]
        public string Display_Format {
            get {
                return ((string)(this["Display_Format"]));
            }
            set {
                this["Display_Format"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Advue_Insertion {
            get {
                return ((bool)(this["Advue_Insertion"]));
            }
            set {
                this["Advue_Insertion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B")]
        public string Pie_Format {
            get {
                return ((string)(this["Pie_Format"]));
            }
            set {
                this["Pie_Format"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E")]
        public string Language {
            get {
                return ((string)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Prime_Time_Summary_Frequency {
            get {
                return ((int)(this["Prime_Time_Summary_Frequency"]));
            }
            set {
                this["Prime_Time_Summary_Frequency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Sports_Summary_Frequency {
            get {
                return ((int)(this["Sports_Summary_Frequency"]));
            }
            set {
                this["Sports_Summary_Frequency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Grid_SBS_Roll_and_Hold {
            get {
                return ((bool)(this["Grid_SBS_Roll_and_Hold"]));
            }
            set {
                this["Grid_SBS_Roll_and_Hold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Grid_Movie_Recap_Roll_and_Hold {
            get {
                return ((bool)(this["Grid_Movie_Recap_Roll_and_Hold"]));
            }
            set {
                this["Grid_Movie_Recap_Roll_and_Hold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Grid_Prime_Time_Roll_and_Hold {
            get {
                return ((bool)(this["Grid_Prime_Time_Roll_and_Hold"]));
            }
            set {
                this["Grid_Prime_Time_Roll_and_Hold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Grid_Sports_Summary_Roll_and_Hold {
            get {
                return ((bool)(this["Grid_Sports_Summary_Roll_and_Hold"]));
            }
            set {
                this["Grid_Sports_Summary_Roll_and_Hold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Grid_Roll_and_Hold {
            get {
                return ((bool)(this["Grid_Roll_and_Hold"]));
            }
            set {
                this["Grid_Roll_and_Hold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VideoVue_Insertion {
            get {
                return ((bool)(this["VideoVue_Insertion"]));
            }
            set {
                this["VideoVue_Insertion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("L")]
        public string Laser_Insertion_Type {
            get {
                return ((string)(this["Laser_Insertion_Type"]));
            }
            set {
                this["Laser_Insertion_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("29")]
        public int Prime_Time_Starting_TimeSlot {
            get {
                return ((int)(this["Prime_Time_Starting_TimeSlot"]));
            }
            set {
                this["Prime_Time_Starting_TimeSlot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int Prime_Time_LookAhead_TimeSlots {
            get {
                return ((int)(this["Prime_Time_LookAhead_TimeSlots"]));
            }
            set {
                this["Prime_Time_LookAhead_TimeSlots"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cycle_Summary_Info {
            get {
                return ((bool)(this["Cycle_Summary_Info"]));
            }
            set {
                this["Cycle_Summary_Info"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Grid_Synopsis {
            get {
                return ((bool)(this["Grid_Synopsis"]));
            }
            set {
                this["Grid_Synopsis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Grid_Synopsis_Roll_and_Hold {
            get {
                return ((bool)(this["Grid_Synopsis_Roll_and_Hold"]));
            }
            set {
                this["Grid_Synopsis_Roll_and_Hold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23")]
        public int Prime_Time_Promotion_Start_TimeSlot {
            get {
                return ((int)(this["Prime_Time_Promotion_Start_TimeSlot"]));
            }
            set {
                this["Prime_Time_Promotion_Start_TimeSlot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("36")]
        public int Prime_Time_Promotion_End_TimeSlot {
            get {
                return ((int)(this["Prime_Time_Promotion_End_TimeSlot"]));
            }
            set {
                this["Prime_Time_Promotion_End_TimeSlot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int Sports_Summary_LookAhead {
            get {
                return ((int)(this["Sports_Summary_LookAhead"]));
            }
            set {
                this["Sports_Summary_LookAhead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int PPV_Display_After_PGM_Start {
            get {
                return ((int)(this["PPV_Display_After_PGM_Start"]));
            }
            set {
                this["PPV_Display_After_PGM_Start"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Cycle_Summary_Frequency {
            get {
                return ((int)(this["Cycle_Summary_Frequency"]));
            }
            set {
                this["Cycle_Summary_Frequency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00")]
        public string System_Default_Brush_ID {
            get {
                return ((string)(this["System_Default_Brush_ID"]));
            }
            set {
                this["System_Default_Brush_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Weather_Roll_and_Hold {
            get {
                return ((bool)(this["Weather_Roll_and_Hold"]));
            }
            set {
                this["Weather_Roll_and_Hold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Military_Time_Flag {
            get {
                return ((bool)(this["Military_Time_Flag"]));
            }
            set {
                this["Military_Time_Flag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleanup_Unused_Logos {
            get {
                return ((bool)(this["Cleanup_Unused_Logos"]));
            }
            set {
                this["Cleanup_Unused_Logos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("H")]
        public string Display_Length_Setting {
            get {
                return ((string)(this["Display_Length_Setting"]));
            }
            set {
                this["Display_Length_Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("142")]
        public int Custom_Display_Length {
            get {
                return ((int)(this["Custom_Display_Length"]));
            }
            set {
                this["Custom_Display_Length"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int Number_of_Colors {
            get {
                return ((int)(this["Number_of_Colors"]));
            }
            set {
                this["Number_of_Colors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("N")]
        public string Text_Ad_Flag {
            get {
                return ((string)(this["Text_Ad_Flag"]));
            }
            set {
                this["Text_Ad_Flag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PC_Disk_Support {
            get {
                return ((bool)(this["PC_Disk_Support"]));
            }
            set {
                this["PC_Disk_Support"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("N")]
        public string Retail_Trade_Zone_Audio {
            get {
                return ((string)(this["Retail_Trade_Zone_Audio"]));
            }
            set {
                this["Retail_Trade_Zone_Audio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Flexible_Grid {
            get {
                return ((bool)(this["Flexible_Grid"]));
            }
            set {
                this["Flexible_Grid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("N")]
        public string Retail_Trade_Zone_System {
            get {
                return ((string)(this["Retail_Trade_Zone_System"]));
            }
            set {
                this["Retail_Trade_Zone_System"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Clock_Command {
            get {
                return ((int)(this["Clock_Command"]));
            }
            set {
                this["Clock_Command"] = value;
            }
        }
    }
}
