//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrevueDataSender {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class PrevueOldConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static PrevueOldConfig defaultInstance = ((PrevueOldConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PrevueOldConfig())));
        
        public static PrevueOldConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public string TimeSlot_Backward_Display {
            get {
                return ((string)(this["TimeSlot_Backward_Display"]));
            }
            set {
                this["TimeSlot_Backward_Display"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E")]
        public string Timeslot_Forward_Display {
            get {
                return ((string)(this["Timeslot_Forward_Display"]));
            }
            set {
                this["Timeslot_Forward_Display"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int Scroll_Speed {
            get {
                return ((int)(this["Scroll_Speed"]));
            }
            set {
                this["Scroll_Speed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("36")]
        public int Number_of_Text_Ads {
            get {
                return ((int)(this["Number_of_Text_Ads"]));
            }
            set {
                this["Number_of_Text_Ads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int Number_of_Text_Ad_Lines {
            get {
                return ((int)(this["Number_of_Text_Ad_Lines"]));
            }
            set {
                this["Number_of_Text_Ad_Lines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Ignore_National_Ads_Flag {
            get {
                return ((bool)(this["Ignore_National_Ads_Flag"]));
            }
            set {
                this["Ignore_National_Ads_Flag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Before_TimeSlot_Minutes {
            get {
                return ((int)(this["Before_TimeSlot_Minutes"]));
            }
            set {
                this["Before_TimeSlot_Minutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int After_TimeSlot_Minutes {
            get {
                return ((int)(this["After_TimeSlot_Minutes"]));
            }
            set {
                this["After_TimeSlot_Minutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int Time_Zone {
            get {
                return ((int)(this["Time_Zone"]));
            }
            set {
                this["Time_Zone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Observe_DST_Flag {
            get {
                return ((bool)(this["Observe_DST_Flag"]));
            }
            set {
                this["Observe_DST_Flag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Continued_Flag {
            get {
                return ((bool)(this["Continued_Flag"]));
            }
            set {
                this["Continued_Flag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Keyboard_Flag {
            get {
                return ((bool)(this["Keyboard_Flag"]));
            }
            set {
                this["Keyboard_Flag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Ten_Minute_Window {
            get {
                return ((bool)(this["Ten_Minute_Window"]));
            }
            set {
                this["Ten_Minute_Window"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Three_Minute_Window {
            get {
                return ((bool)(this["Three_Minute_Window"]));
            }
            set {
                this["Three_Minute_Window"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ignore_VCR_Plus_Flag {
            get {
                return ((bool)(this["Ignore_VCR_Plus_Flag"]));
            }
            set {
                this["Ignore_VCR_Plus_Flag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("N")]
        public string Laser_Format {
            get {
                return ((string)(this["Laser_Format"]));
            }
            set {
                this["Laser_Format"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Y")]
        public string Graphic_Ads_Enabled_Flag {
            get {
                return ((string)(this["Graphic_Ads_Enabled_Flag"]));
            }
            set {
                this["Graphic_Ads_Enabled_Flag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("N")]
        public string Video_Insertion_Enabled_Flag {
            get {
                return ((string)(this["Video_Insertion_Enabled_Flag"]));
            }
            set {
                this["Video_Insertion_Enabled_Flag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Time_Zone_Minutes_Adjustment {
            get {
                return ((int)(this["Time_Zone_Minutes_Adjustment"]));
            }
            set {
                this["Time_Zone_Minutes_Adjustment"] = value;
            }
        }
    }
}
